### ISSUE TITLE
Unable to resolve './DrawerLayout'

### ISSUE THREAD

**Issue by msukmanowsky** [react-navigation/drawer#47] opened 2019-02-02 02:04 UTC
**Issue**

While building a new app with Expo, I'm encountering this error:

```
Unable to resolve "./DrawerLayout" from "node_modules/react-navigation-drawer/dist/views/DrawerView.js"
```

**Dependencies**

```
  "dependencies": {
    "expo": "^32.0.3",
    "firebase": "^5.8.2",
    "prop-types": "^15.6.2",
    "react": "^16.7.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz",
    "react-native-elements": "^1.0.0",
    "react-native-emoji": "^1.3.1",
    "react-native-sideswipe": "^1.4.2",
    "react-navigation": "^3.1.2"
  },
  "devDependencies": {
    "babel-preset-expo": "^5.0.0",
    "prettier": "1.16.1",
    "schedule": "^0.4.0"
  },
```

**Relevant Package Versions Installed**

```
react-navigation-drawer@1.1.0
react-native-gesture-handler@1.0.15
```

What's odd is that the import in `node_modules/react-navigation-drawer/dist/views/DrawerView.js` seems fine

```
import DrawerLayout from 'react-native-gesture-handler/DrawerLayout';
```

That module exists and has a default class export which is `DrawerLayout`.

**Comment by msukmanowsky** [comment] 2019-02-02 02:08
Wondering if this is maybe a conflict with Expo?

```
$ find node_modules -name "DrawerLayout.js"
node_modules/expo/node_modules/react-native-gesture-handler/DrawerLayout.js
node_modules/react-native-gesture-handler/DrawerLayout.js
```

**Comment by msukmanowsky** [comment] 2019-02-03 02:09
Ended up sorting this out by pinning react-navigation to exactly `3.0.9`

```
  "dependencies": {
    "expo": "^32.0.3",
    "firebase": "^5.8.2",
    "prop-types": "^15.6.2",
    "react": "16.5.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz",
    "react-native-elements": "^1.0.0",
    "react-native-emoji": "^1.3.1",
    "react-native-sideswipe": "^1.4.2",
    "react-navigation": "3.0.9"
  },
```

**Comment by NichAga** [comment] 2019-02-04 16:48
Yes but this souldn't be closed, since it currently affects my native app too, not only expo

**Comment by carlosdimatteo** [comment] 2019-02-08 21:08
I suddenly started having this issue too , im using Yarn though

**Comment by satya164** [comment] 2019-02-08 21:11
Does anyone have a repo which I can check?

**Comment by sharkeyjack11** [comment] 2019-02-08 22:21
I have it too using npm

**Comment by ObiKerui** [comment] 2019-02-09 15:13
I have this issue now too after upgrading to version 3.2.0. I'm not using Expo either.

**Comment by alainduchateau** [comment] 2019-02-10 09:22
Rolling back to 3.0.9 seems functional, thank you !

**Comment by prionkor** [comment] 2019-04-02 09:14
I am using expo and this issue still persists. 

Expo: `v32.0.6`
React Navigation: `v3.6.0`

Installing react navigation version `v3.0.9` breaks with the error "Tried to register two views with same name RNGestureHandlerButton"

NOTE: The package `react-native-gesture-handler` is not installed via npm as it is part of expo.

**Comment by Yajan** [comment] 2019-05-09 07:05
I am getting this error when I update my react-navigation to the latest version i.e 3.9.1. I am using expo

Here is my packages

```
expo: "^32.0.0",
react: "^16.8.6",
react-ar": "^16.8.6",
react-dom: "^16.8.6",
react-native: "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz",
react-native-paper: "^2.15.2",
react-native-web: "^0.11.2",
react-navigation: "^3.9.1",
```
Rolling back to 3.0.9 resolves the issues but I want the latest version for a bug fix.

**Comment by satya164** [comment] 2019-05-09 10:37
This issue is likely caused by metro's cache. If you're facing this issue, make sure:
- You're on latest version of react-navigation
- If you don't use expo, ensure you have the latest version of react-native-gesture-handler
- If you are on expo, run `expo start -c` to clear metro cache
- If you are not on expo, run `react-native start --reset-cache`

I'm closing this since this is not actionable for us. If you believe this is a bug in the library, please open an issue with a runnable repro in a gthub repo.

**Closed by satya164** 2019-05-09 10:37 UTC

**Comment by elie222** [comment] 2019-08-14 20:09
For others that run into this, the following may help:

```sh
expo install react-native-gesture-handler
```

**Comment by isoume** [comment] 2019-08-17 12:00
Hello,
I have the same problem :
I am using version 3.11.1 of react-navigation and it say the module AppRegistry is not a refistered callable module.

"dependencies": {
    "expo": "^34.0.1",
    "react": "16.8.3",
    "react-dom": "^16.8.6",
    "react-native": "https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz",
    "react-native-web": "^0.11.4",
    "react-navigation": "^3.11.1"
  }

error : 
Unable to resolve "react-native-gesture-handler/DrawerLayout" from "node_modules\react-navigation-drawer\dist\views\DrawerView.js"
Failed building JavaScript bundle.
